### ISSUE TITLE
internal error: environment misses: dir

### ISSUE THREAD

**Issue by sxq112358** [haltcase/glob#60]
Compile failed when use `walkGlob` or `walkGlobKinds` inside an iterator.
```
import os
import glob
proc test()=
    let it = iterator():string=
        for path in walkGlob("*","./"):
            yield path
test()
```
when compiling, it gives the following error:
`/home/***/.nimble/pkgs/glob-0.11.2/glob.nim(512, 33) Error: internal error: environment misses: dir`

Nim Compiler Version 1.6.12 [Linux: amd64] on Archlinux
and Nim Compiler Version 1.6.12 [Windows: amd64] on Windows11

**Comment by haltcase** [comment]
Looks like this is the source of the error, but I don't have any idea what the cause is. `dir` is defined on L506 and used shortly thereafter on L512:

https://github.com/haltcase/glob/blob/64f71af2fa4572c2bdf8987a56a427c1d88fc34f/src/glob.nim#L506-L512

Contributions/help investigating would be welcome for this one.

**Comment by sxq112358** [comment]
Minimal reproducible example

```nim
from sequtils import toSeq

iterator test(dir:int):int=
  yield 1234

iterator walkGlobKinds (): int =
  let dir = 123
  let it = test(dir).toSeq()           #fail
  #let it3 = countup(0,dir,2).toSeq()  #fail

  #let it2 = collect:
  #  for i in test(dir):i  #pass

  #for i in test(dir):
  #  echo i                #pass


proc main()=
    let it = iterator():int=
        for path in walkGlobKinds():
            yield path
main()
```

It could be a bug in nim compiler?

**Comment by sxq112358** [comment]
the compiler bug has been fixed. [nim issue link](https://github.com/nim-lang/Nim/issues/21737)
